# Generated by Django 4.2.2 on 2023-07-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_review_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('added_date',)},
        ),
    ]
