# Generated by Django 4.2.2 on 2023-07-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_comment_edited_date_alter_review_edited_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('added_date',)},
        ),
    ]
