# Generated by Django 4.2.2 on 2023-07-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('added_date',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-added_date',)},
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='books', to='books.genre', verbose_name='Жанр'),
        ),
    ]
