# Generated by Django 4.2.2 on 2023-08-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_genre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'author')},
        ),
    ]
