# Generated by Django 4.2.2 on 2023-08-05 19:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_book_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_book_to_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 8, 6))], verbose_name='Дата рождения'),
        ),
    ]
