# Generated by Django 4.2.2 on 2023-08-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_show_book_read_user_show_book_to_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_book_read',
            field=models.BooleanField(default=True, verbose_name='Показывать другим пользователям список прочитанных книг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_book_to_read',
            field=models.BooleanField(default=True, verbose_name='Показывать другим пользователям список запланированных книг'),
        ),
    ]
